name: Sync to GitLab

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  gitlab-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/Hackjunior1/NaukariProfileUpdater.git"

      - name: Mirror push to GitLab
        run: |
          git push mirror gitlab
          git push gitlab --tags
