name: Sync to GitLab
on:
  push:
    branches:
      - main  # Or your primary branch name
  workflow_dispatch: # Allows manual sync from the Actions tab
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to get all history
      - name: Mirror to GitLab
        run: |
          git push --mirror https://oauth2:${{ secrets.GITLAB_TOKEN }}//git@gitlab.com:Hackjunior1/NaukariProfileUpdater.git
